# Usar Python 3.12 como base
FROM python:3.12-slim

# Definir o diretório de trabalho
WORKDIR /app

# Copiar o script Python para dentro do container
COPY carguru.py /app/carguru.py

# Comando para executar o script
CMD ["python", "carguru.py"]
