# Usar imagem base do Python
FROM python:3.12-slim

# Definir diretório de trabalho no container
WORKDIR /app

# Copiar apenas o script Python para o container
COPY main.py /app/

# Comando de execução
CMD ["python", "main.py"]
